
services:

  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - mongo-data:/data/db
    env_file:
      - .env
    command: mongod --logpath /dev/null
    ports:
      - "27017:27017"
    networks:
      - node-network

  db-admin:
    image: mongo-express
    container_name: db-admin
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mongo-data:
