
services:

  db:
    image: mongo:latest
    container_name: db
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGODB_LOG_VERBOSITY=0
    command: mongod --logpath /dev/null
    ports:
      - "27017:27017"
    networks:
      - node-network

  db-admin:
    image: mongo-express
    container_name: db-admin
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    networks:
      - node-network

networks:
  node-network:
    driver: bridge

volumes:
  mongo-data:
